### ISSUE TITLE
[question] Write text and bitmaps...

### ISSUE THREAD

**Issue by codewarriorFX** [MartyMacGyver/OLED_SSD1322#1]
Hi - Do you have any example to write text and bitmaps to the ssd1322 oled? Im using a 2560 rev3 board.

**Comment by MartyMacGyver** [comment]
I don't offhand (it's been a while since I've used it) but I see others have worked with text:

https://github.com/harlequin-tech/OledHQ

**Comment by MartyMacGyver** [comment]
(Closing this as it's not an issue per se, but feel free to continue commenting on this thread if you have further questions.)
